---
title: "COVID-19 data portal -- monthly report"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(wordcloud2)
#library(shiny)
setwd("~/data_portal")
source("scripts/dev/reports/report.R")
cols <- c("f67453", "#4c8286", "#6dbbc0", "#8ca14b", "#b0ca5e", "#ffd500", "#edb335", "#e75b42", "#c2204d", "#de3765", "#ddff99")
```

Performance
========================================

Row
-----------------------------------------
### Indicators in total

```{r}
totalInd <- df_events$ind_count_cum[length(df_events$ind_count_cum)]
valueBox(value = totalInd, color = "primary")
```

### Indicators added last month
```{r}
valueBox(value = df_events$new_inds[length(df_events$new_inds)], 
         color = ifelse(df_events$new_inds[length(df_events$new_inds)] > 0, "success", "warning"),
         icon = ifelse(df_events$new_inds[length(df_events$new_inds)] > 0, "fa-angle-double-up", "fa-angle-double-down"))
```

### Change in visits
```{r}
latest_views <- df_events$views_count[df_events$month == latest_report_date]
previous_views <- df_events$views_count[df_events$month == latest_report_date %m-% months(1)]
perc_change <- round(latest_views / previous_views * 100 - 100, 1)
valueBox(value = paste0(perc_change, "%"), 
         color = ifelse(previous_views > latest_views, "warning", "success"), 
         icon = ifelse(previous_views > latest_views, "fa-angle-double-down", "fa-angle-double-up"))
```

### Percent downloaded
```{r}
perc_downloaded <- round(df_events$download_count[df_events$month == latest_report_date] / df_events$views_count[df_events$month == latest_report_date] * 100, 1)
valueBox(value = paste0(perc_downloaded, "%"), caption = "of visits ended in download", color = "primary")
```

Row
----------------------------------------
### Number of indicators

```{r}
y_vis<- list(
  tickfont = list(color = "#de3765"),
  overlaying = "y",
  side = "right",
  title = "Montly visits",
  zeroline = FALSE, showline = FALSE
)
text_main <- ~paste0(format(x = df_events$month,  "%B"), ': ', df_events$ind_count_cum)
text_views <- ~paste0(format(x = df_events$month,  "%B"), ': ', df_events$views_count)
text_downloads <- ~paste0(format(x = df_events$month,  "%B"), ': ', df_events$download_count)

fig1 <- plot_ly(
  x = df_events$month,
  y = df_events$ind_count_cum,
  type = "bar",
  name = "Number of indicators",
  marker = list(color = "#838f9c", line = list(color = "#5a6776")),
  hoverinfo = 'text', 
  text = text_main
)

fig1 <- fig1 %>% add_lines(x = df_events$month, y = df_events$views_count, name = "Monthly visits", yaxis = "y2", marker = list(color = "#de3765"), text = text_views)
fig1 <- fig1 %>% add_lines(x = df_events$month, y = df_events$download_count, name = "Monthly downloads", yaxis = "y2", marker = list(color = "#4c8286"), text = text_downloads)
fig1 <- fig1 %>% layout(title = "Number of indicators overlayed wth monthly visits",
                        yaxis2 = y_vis,
                        xaxis = list(title = "Month", zeroline = FALSE, showline = FALSE),
                        xaxis2 = list(zeroline = FALSE, showline = FALSE))

fig1

```


Row
------------------------------------------

### Loaded into Open Data API
```{r}
opi <- length(unique(df_indicators$indicator_name[!is.na(df_indicators$ResourceID)]))
gauge(opi, min = 0, max = totalInd, gaugeSectors(
  success = c(floor(totalInd*0.66), totalInd), warning = c(floor(totalInd*0.33), floor(totalInd*0.66)), danger = c(0, floor(totalInd*0.33))
))
```

### Automated updates
```{r}
automated <- length(unique(df_indicators$indicator_name[!is.na(df_indicators$script)]))
gauge(automated, min = 0, max = totalInd, gaugeSectors(
  success = c(floor(totalInd*0.66), totalInd), warning = c(floor(totalInd*0.33), floor(totalInd*0.66)), danger = c(0, floor(totalInd*0.33))
))
```

Summary
============================================================

Row {data-height = 300}
-----------------------------------------

### Sub-series
```{r}
no_sub <- sum(df_indicators$no_subseries)
subs <- df_events$ind_count_cum[length(df_events$ind_count_cum)] - no_sub
vals <- c(no_sub,
          subs)
labs <- c("No sub-series",
          "Sub-series")

fig <- plot_ly(labels = labs, values = vals,
                        textposition = 'inside',
                        textinfo='percent', 
                        hoverinfo = 'text',
                        text = ~paste0(labs, ': ', vals, ' indicators'),
                        marker = list(colors = c("#b0ca5e", "#6dbbc0")))
fig <- fig %>% add_pie(hole = 0.6)
fig <- fig %>% layout(title = "",  showlegend = TRUE,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```

### Downloadable
```{r}
data <- df_indicators %>% 
  select(indicator_name, download) %>%
  unique() %>% 
  group_by(download) %>% 
  summarise(count = n())

vals <- c(data$count[data$download == TRUE], data$count[data$download == FALSE])
labs <- c("Downloadable", "Non-downloadable")
fig <- data %>% plot_ly(
  labels = labs, 
  values = vals, 
  textinfo='percent', 
  textposition = 'inside',
  hoverinfo = 'text',
  text = ~paste0(labs, ": ", vals, ' indicators'),
  marker = list(colors = c("#edb335", "#de3765")))
fig <- fig %>% add_pie(hole = 0.6)
fig <- fig %>% layout(title = "",  showlegend = TRUE,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Most/least visited indicators

```{r}
ind_views_total <- df_ind_views %>% 
  select(indicator_name, ind_views) %>% 
  group_by(indicator_name) %>% 
  summarise(total_views = sum(ind_views))

ind_views_total <- df_indicators %>% 
  select(indicator_name) %>% 
  unique() %>% 
  left_join(ind_views_total) 

ind_views_total <- df_ind_views %>% 
  filter(month == latest_report_date) %>% 
  select(indicator_name, ind_views) %>% 
  right_join(ind_views_total)

most_viewed <- ind_views_total %>% 
  select(indicator_name, total_views, ind_views) %>% 
  #filter(total_views > 999) %>% 
  arrange(desc(total_views))

# least_viewed <- ind_views_total %>% 
#   select(indicator_name, total_views, ind_views) %>% 
#   filter(total_views < 10) %>% 
#   arrange(total_views)
# least_viewed$ind_views <- ifelse(is.na(least_viewed$ind_views), 0, least_viewed$ind_views)

names(most_viewed) <- c("Indicator name", "Total views", "Views last month")

library(DT)
DT::datatable(most_viewed, rownames = FALSE, options = list(pageLength = 5))

#knitr::kable(most_viewed, col.names = c("Indicator name", "Total views", "Views last month"))
```


### Number of indicators by sub-series
```{r}
region <- df_indicators %>% 
  filter(region) %>% 
  select(indicator_name) %>% 
  unique() %>% 
  nrow()
gender <- df_indicators %>% 
  filter(gender) %>% 
  select(indicator_name) %>% 
  unique() %>% 
  nrow()
age <- df_indicators %>% 
  filter(age) %>% 
  select(indicator_name) %>% 
  unique() %>% 
  nrow()
ethnic <- df_indicators %>% 
  filter(ethnic) %>% 
  select(indicator_name) %>% 
  unique() %>% 
  nrow()
industry <- df_indicators %>% 
  filter(industry) %>% 
  select(indicator_name) %>% 
  unique() %>% 
  nrow()
other <- df_indicators %>% 
  filter(other) %>% 
  select(indicator_name) %>% 
  unique() %>% 
  nrow()
vals <- c(region, gender, age, ethnic, industry, other)
labs <- c("By region", "By gender", "By age", "By ethnicity", "By industry", "Other sub-series")
data <- data.frame(labs = labs, vals = vals) %>% arrange(desc(vals))
knitr::kable(data, col.names = c("Series", "Number of indicators"), align = "l")
```


Brokerage
============================================================
Row {data-height = 300}
-----------------------------------------
### Frequency
```{r}

data <- df_indicators %>% 
  select(indicator_name, frequency) %>% 
  unique() %>% 
  group_by(frequency) %>% 
  summarise(count = n())
  
  
fig <- data %>% plot_ly(labels = ~frequency, values = ~count,
                        textposition = 'inside',
                        textinfo='percent', 
                        hoverinfo = 'text',
                        text = ~paste0(frequency, ': ', count, ' indicators'),
                        marker = list(colors = cols))
fig <- fig %>% add_pie(hole = 0.6)
fig <- fig %>% layout(title = "",  showlegend = TRUE,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```

### Sourcing
```{r}

data <- df_indicators %>% 
  select(indicator_name, sourcing) %>% 
  unique() %>% 
  group_by(sourcing) %>% 
  summarise(count = n())
  
  
fig <- data %>% plot_ly(labels = ~sourcing, values = ~count,
                        textposition = 'inside',
                        textinfo='percent', 
                        hoverinfo = 'text',
                        text = ~paste0(sourcing, ': ', count, ' indicators'),
                        marker = list(colors = cols))
fig <- fig %>% add_pie(hole = 0.6)
fig <- fig %>% layout(title = "",  showlegend = TRUE,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### New indicators added last month
```{r}
data <- df_indicators %>% 
  filter(month == latest_report_date) %>% 
  select(indicator_name, source, frequency) %>% 
 left_join(df_ind_views) %>% 
  select(-month) %>% 
  unique() %>% 
  arrange(desc(ind_views))
knitr::kable(data, col.names = c("Indicator name", "Source", "Frequency", "Views last month"))
```

### Largest suppliers
```{r}
data <- df_indicators %>% 
  select(indicator_name, source) %>% 
  unique() %>% 
  group_by(source) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))
# %>% 
#   head(n = 10)

data_views <- df_ind_views %>% 
  select(indicator_name, ind_views) %>% 
  group_by(indicator_name) %>% 
  summarise(total_views = sum(ind_views)) %>% 
  left_join(df_indicators) %>% 
  select(indicator_name, source, total_views) %>% 
  group_by(source) %>% 
  summarize(source_views = sum(total_views)) %>% 
  right_join(data) %>% 
  arrange(desc(count)) %>% 
  select(source, count, source_views)
  

#knitr::kable(data_views, col.names = c("Supplier", "Number of indicators", "Total views"))

names(data_views) <- c("Supplier", "Number of indicators", "Total views")

library(DT)
DT::datatable(data_views, rownames = FALSE, options = list(pageLength = 5))

```
